services:
  service:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      search:
        condition: service_started
      cache:
        condition: service_started
    networks:
      - moviesnetwork

  search:
    image: krissmelikova/awesome_repository:v1
    volumes:
      - .es/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
       test: curl -s http://fastapi-solutions-search-1:9200
       interval: 30s
       timeout: 10s
       retries: 50
    networks:
      - moviesnetwork

  cache:
    image: redis:7.2.4-alpine
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
     - ./redis-data:/var/lib/redis
    networks:
      - moviesnetwork

networks:
  moviesnetwork:
